### PR TITLE
feat(app): 110 Applying methods to RigidBodies

### LINKED ISSUE #104: Demos: apply forces
### Description

I would like to have some demos in this repo, applying basic forces 

### Suggested solution

_No response_

### Alternative

_No response_

### Additional context

_No response_

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/rapier/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/rapier/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://rapier.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/rapier/issues) that reports the same bug to avoid creating a duplicate.

### LINKED ISSUE #110: Applyng method to RigidBodies
### Description

Right now we can apply any force, the object is not being exported and even doing it, tryng to applyng any force, doesn't throw an error but, do nothing

### Suggested solution

Could be something like (currently this is not doing anything):
```
const jumpCube = () => {
  if (rigidCubeRef.value) {
    rigidCubeRef.value.instance[0].rigidBody.applyImpulse({ x: 0, y: 1, z: 0 })
  }
}
```
We can expose some object like:

```
defineExpose({
  instance: rigidBodyInfos,
  collider: colliderInfos,
})
```

### Alternative

_No response_

### Additional context

_No response_

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/rapier/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/rapier/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://rapier.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/rapier/issues) that reports the same bug to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by JaimeTorrealba**
closes #110 
closes #104 

For now, I just moved the logic of the instance into a new component InstanceRigidBody (Then based on the Discord discussion we can change it or tweak it)

Expose and add demo for applying methods (like force, impulse, etc)

I would like to merge this to be able to continue, please.

I decided to expose the following structure, let me know if you have any feedback (I found this one appropriated for the case)

```
defineExpose({
  instance: rigidBodyInstance,
  rigidBodyInfos,
  collider: colliderInfos,
  group: parentObject,
})
```

### CODE REVIEW

**Comment by JaimeTorrealba** [comment]
@Neosoulink no problem now this repo is in heavy development, and frankly colliders are more important.

But in your PR we should try to have all the things here:
Expose the right methods instances, etc. proper docs, InstanceRgidBody, demos. Maybe worth merging this one's in yours.

PRs too big are difficult to review them

**Comment by JaimeTorrealba** [comment]
@Neosoulink Same with this one, my friend, and sorry to make you deal with all the conflict, I'll not touch the RigidBody until you finish with collider.

Please next time write me so we avoid unnecessary git conflicts, :) I'm here to help

**Comment by Neosoulink** [comment]
Hey @JaimeTorrealba 

No No, don't worry, I'm glad to see activity on this project!

I can handle the small conflicts ahah

**Review by Neosoulink — APPROVED** [review]
LGTM ✅

Aside `RIgidBody`, there are no major code conflicts with my changes

**Pull request merged**
